# Generated by Django 4.1.4 on 2022-12-11 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_fecha_termino_task_fecha_creada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='fecha_creada',
            new_name='fecha_termino',
        ),
    ]
